# Name of the county for file naming purposes
COUNTY_NAME: "Sample County"

# Path to the census tract shapefile for this county
TRACT_PATH: "./data/sample_census_tracts.geojson"
# Name of the variable in TRACT_PATH referring to the GEOID
TRACT_GEOID_VARNAME: "GEOID"

# Path to the indicator data at the census tract level for this county
TRACT_DATA_PATH: "./data/sample_housing_loss_indicator_data.csv"
# Name of the variable in TRACT_DATA_PATH referring to the GEOID
TRACT_DATA_GEOID_VARNAME: "geoid"
# Name of the variable in TRACT_DATA_PATH to use as measure of housing loss
HOUSING_LOSS_VARNAME: "housing-loss-index"

# Path to the POI shapefile for this county
POI_PATH: "./data/sample_event_sites.geojson"
# Name of the variable in POI_PATH referring to poi type
POI_TYPE_VARNAME: "type"
# List of types contained in POI_TYPE_VARNAME that are acceptable as event sites
POI_TYPES:
  - "library"

# Distance around tracts of interest to search for potential event sites
DISTANCE_RADIUS_M: 10000

# List of variables in TRACT_DATA_PATH positively correlated with housing loss
POS_CORR_VARS:
  - "pct-with-snap-benefits"
  - "pct-renter-occupied"
  - "pct-without-health-insurance"
# List of variables in TRACT_DATA_PATH negatively correlated with housing loss
NEG_CORR_VARS:
  - "pct-households-with-children"
  - "pct-own-computer"
