# Name of the county for file naming purposes
COUNTY_NAME:

# Path to the census tract shapefile for this county
TRACT_PATH:
# Name of the variable in TRACT_PATH referring to the GEOID
TRACT_GEOID_VARNAME:

# Path to the indicator data at the census tract level for this county
TRACT_DATA_PATH:
# Name of the variable in TRACT_DATA_PATH referring to the GEOID
TRACT_DATA_GEOID_VARNAME:
# Name of the variable in TRACT_DATA_PATH to use as measure of housing loss
HOUSING_LOSS_VARNAME:

# Path to the POI shapefile for this county
POI_PATH:
# Name of the variable in POI_PATH referring to poi type
POI_TYPE_VARNAME:
# List of types contained in POI_TYPE_VARNAME that are acceptable as event sites
POI_TYPES:

# Distance around tracts of interest to search for potential event sites
DISTANCE_RADIUS_M:

# List of variables in TRACT_DATA_PATH positively correlated with housing loss
POS_CORR_VARS:
# List of variables in TRACT_DATA_PATH negatively correlated with housing loss
NEG_CORR_VARS:
